import tseslint from '@typescript-eslint/eslint-plugin';
import tsparser from '@typescript-eslint/parser';
import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        project: ['./tsconfig.json'],
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
    },
    rules: {
      'no-unused-vars': 'off',
      'prefer-const': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      'indent': ['error', 2],
      'linebreak-style': 0,
      'quotes': ['warn', 'double', { 'avoidEscape': true }],
      'semi': ['error', 'always'],
      'no-tabs': ['error'],
      'no-loss-of-precision': 'error',
      'no-floating-decimal': 'error',
      'eqeqeq': 'error',
      'no-multi-spaces': ['error', { 'exceptions': { 'VariableDeclarator': true } }],
      'for-direction': 'error',
      'no-template-curly-in-string': 'warn',
      'no-unreachable': 'warn',
      'no-unreachable-loop': 'warn',
      'no-unsafe-optional-chaining': 'warn',
      'block-scoped-var': 'warn',
      'curly': 'error',
      'default-case': 'error',
      'default-case-last': 'error',
      'default-param-last': 'error',
      'dot-location': ['error', 'property'],
      'dot-notation': 'error',
      'grouped-accessor-pairs': ['error', 'getBeforeSet'],
      'no-alert': 'error',
      'no-constructor-return': 'error',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-implied-eval': 'error',
      'no-invalid-this': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'error',
      'no-loop-func': 'error',
      'no-multi-str': 'error',
      'no-new': 'warn',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-proto': 'error',
      'no-script-url': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'warn',
      'no-unmodified-loop-condition': 'error',
      'no-unused-expressions': ['warn', { 'allowShortCircuit': true, 'allowTernary': true }],
      'no-useless-call': 'error',
      'no-useless-concat': 'warn',
      'no-void': 'error',
      'yoda': 'error',
      '@typescript-eslint/no-shadow': 'error',
      'no-undef-init': 'error',
      'array-bracket-spacing': ['error', 'never'],
      'block-spacing': 'error',
      'brace-style': ['error', 'stroustrup'],
      'camelcase': ['error', { 'ignoreDestructuring': true, 'ignoreImports': true, 'ignoreGlobals': true }],
      'comma-dangle': ['error', 'always-multiline'],
      'comma-spacing': 'error',
      'comma-style': ['error', 'last'],
      'computed-property-spacing': ['error', 'never'],
      'eol-last': 'error',
      'func-call-spacing': ['error', 'never'],
      'func-name-matching': 'error',
      'function-call-argument-newline': ['error', 'consistent'],
      'function-paren-newline': ['error', 'consistent'],
      'implicit-arrow-linebreak': ['error', 'beside'],
      'key-spacing': ['warn', {
        'multiLine': {
          'beforeColon': false,
          'afterColon': true
        },
        'align': {
          'beforeColon': true,
          'afterColon': true,
          'on': 'colon'
        }
      }],
      'keyword-spacing': ['error', { 'before': true, 'after': true }],
      'max-depth': ['warn', 2],
      'max-len': ['warn', 150],
      'max-nested-callbacks': ['warn', 2],
      'max-params': ['warn', 5],
      'max-statements-per-line': ['error', { 'max': 1 }],
      'new-parens': 'error',
      'no-array-constructor': 'error',
      'no-multiple-empty-lines': 'error',
      'no-whitespace-before-property': 'error',
      'object-curly-newline': ['error', { 'consistent': true }],
      'object-curly-spacing': ['error', 'always'],
      'object-property-newline': ['error', { 'allowAllPropertiesOnSameLine': true }],
      'operator-linebreak': ['error', 'before'],
      'padded-blocks': ['error', 'never'],
      'semi-spacing': 'error',
      'semi-style': ['error', 'last'],
      'space-before-blocks': 'error',
      'space-before-function-paren': ['error', {
        'anonymous': 'never',
        'named': 'never',
        'asyncArrow': 'always'
      }],
      'space-in-parens': ['error', 'never'],
      'space-infix-ops': 'error',
      'space-unary-ops': ['error', { 'words': true, 'nonwords': false }],
      'spaced-comment': ['error', 'always'],
      'switch-colon-spacing': 'error',
      'template-tag-spacing': ['error', 'never'],
      'unicode-bom': ['error', 'never'],
      'wrap-regex': 'error'
    }
  }
];
